[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pseudovelo"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
license = "BSD-3-Clause"

dependencies = [
    "scipy",
    "numpy",
    "matplotlib",
    "statsmodels",
    "joblib",
    "anndata",
    "pandas",
    "scvelo"
]
[tool.setuptools.packages.find]
include = ["pseudovelo*"]
exclude = ["data*", "reproducibility*"]